version: "3.8"
services:
  postgres:
    image: postgres:14.5-bullseye
    container_name: ${DATABASE_CONTAINER_NAME}
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d

